### ISSUE TITLE
How to make dynamic runtime switch between LTR & RTL in rtlcss?

### ISSUE THREAD

**Issue by amrdarwish1975** [MohammadYounes/rtlcss#104]
Hello,
If I have an application supporting English & Arabic language, how can I switch (in run-time) between LTR & RTL in rtlcss?

**Comment by MohammadYounes** [comment]
Hello, 

You've already asked the same question before (#103), If my response didn't answer your question, you should have said so and continued the discussion there.

Would you please explain in more details what you mean by switch at run time ?


Thanks.

**Comment by amrdarwish1975** [comment]
Please accept my apologies .. you are right. by  switch at run time is that how would setting language would be wired to html tag dir. Normally when user likes to mirror the interface this would be switch from English interface to Arabic interface (like EN/AR button in upper banner of main page in website)

**Comment by MohammadYounes** [comment]
It depends on the application, in case you are able to switch all text in-place, you'll need to switch the stylesheet to the RTL version. Otherwise, you'll hit the server and request a page matching the requested locale linking to the appropriate stylesheet (LTR or RTL) based on the selected language direction. 

If you don't want to have two different stylesheet per language direction, you can use https://github.com/jakob101/postcss-inline-rtl to generate one stylesheet that depends on `html` direction attribute.

Thanks.
