### ISSUE TITLE
Webpack import support

### ISSUE THREAD

**Issue by ismailbayram** [MohammadYounes/rtlcss#113]
I have trying fix a bug about :raw:ignore:begin/end feature. So i found the problem. It is import issue. I've imported a file between ignore:begin/end blocks. It doesnt work. So I create the another file and copied content of imported file and write ignore:begin/end blocks to it. It worked! So I wondered if there is a problem ? 

```
/*rtl:begin:ignore*/
@import "../../node_modules/lightslider/dist/css/lightslider.css";
/*rtl:end:ignore*/
```

**Comment by MohammadYounes** [comment]
@ismailbayram This is because the imported `css` content is placed before any other content in the file. So your example will produce:

```css
[contents of lightslider.css]
/*rtl:begin:ignore*/
/*rtl:end:ignore*/
```

A simple workaround is to create two files:

 * **begin-rtl-ignore.css**  containing the begin directive:
    ```css
    /*!rtl:begin:ignore*/
    
    ```
 * **end-rtl-ignore.css** containing the end directive:
    ```css
    /*!rtl:end:ignore*/
    ```
Then do your import in between:

```css
@import 'begin-rtl-ignore.css';
@import "../../node_modules/lightslider/dist/css/lightslider.css";
@import 'end-rtl-ignore.css';
```
Which will give you:

```css
/*!rtl:begin:ignore*/
[contents of lightslider.css]
/*!rtl:end:ignore*/
```

Thanks!
